<?php
/**
 * @author Gerard van Helden <gerard@zicht.nl>
 * @copyright Zicht Online <http://zicht.nl>
 */
namespace Zicht\Bundle\MenuBundle\Admin;

use \Sonata\AdminBundle\Datagrid\DatagridMapper;
use \Sonata\AdminBundle\Form\FormMapper;
use \Zicht\Bundle\MenuBundle\Entity;
use \Zicht\Bundle\FrameworkExtraBundle\Admin\TreeAdmin;

class MenuItemAdmin extends TreeAdmin
{
    public function configureFormFields(FormMapper $formMapper)
    {
        parent::configureFormFields($formMapper);
        $formMapper
            ->add('path', 'zicht_url', array('required' => false))
            ->add('name')
        ;

        $formMapper->setHelps(array(
            'name' => 'help.name'
        ));
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub

        $filter
            ->add('title')
            ->add('path')
        ;
    }
}